@extends('layouts.admin')
@section('title','Media') @section('page_title','Media')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center mb-4"><div><h1>Media</h1><p>Manage press and media coverage.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#addMedia"><i class="bi bi-plus-lg"></i> Add Media</button></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form class="panel settings-panel mb-4" method="POST" action="{{ route('admin.media.settings') }}">@csrf @method('PUT')<div class="panel-head"><div><h3>Page Settings</h3></div></div><div class="settings-body row g-3"><div class="col-md-4"><label class="form-label">Page Title</label><input class="form-control" name="media_page_title" value="{{ $settings->media_page_title?:'Media' }}" required></div><div class="col-md-4"><label class="form-label">Section Title</label><input class="form-control" name="media_section_title" value="{{ $settings->media_section_title?:'Media' }}" required></div><div class="col-md-4"><label class="form-label">Button Text</label><input class="form-control" name="media_button_text" value="{{ $settings->media_button_text?:'Read More' }}" required></div><div class="col-12 text-end"><button class="btn btn-admin-primary">Save Settings</button></div></div></form>
<div class="row g-3">@forelse($items as $item)<div class="col-12 col-sm-6 col-lg-4"><article class="gallery-admin-card"><a class="gallery-admin-image d-block" href="{{ $item->url }}" target="_blank"><img src="{{ $item->image_url }}" alt="{{ $item->title }}"><span class="gallery-status {{ $item->is_active?'active':'inactive' }}">{{ $item->is_active?'Active':'Inactive' }}</span></a><div class="gallery-admin-body"><div><h3>{{ $item->title }}</h3><small>{{ $item->published_at?->format('d M Y') }} · Order: {{ $item->sort_order }}</small></div><div class="d-flex gap-1"><button class="btn btn-sm btn-light border edit-media" data-bs-toggle="modal" data-bs-target="#editMedia" data-id="{{ $item->id }}" data-title="{{ $item->title }}" data-url="{{ $item->url }}" data-date="{{ $item->published_at?->format('Y-m-d') }}" data-order="{{ $item->sort_order }}" data-active="{{ $item->is_active?1:0 }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.media.destroy',$item) }}" onsubmit="return confirm('Delete this media item?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></div></article></div>@empty<div class="col-12"><div class="panel text-center py-5 text-secondary">No media items found.</div></div>@endforelse</div><div class="mt-4">{{ $items->links() }}</div>
@include('admin.media.partials.modal',['id'=>'addMedia','title'=>'Add Media','formId'=>'addMediaForm','action'=>route('admin.media.store'),'editing'=>false])
@include('admin.media.partials.modal',['id'=>'editMedia','title'=>'Edit Media','formId'=>'editMediaForm','action'=>'#','editing'=>true])
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-media').forEach(b=>b.addEventListener('click',()=>{const f=document.getElementById('editMediaForm');f.action=`{{ url('/admin/media') }}/${b.dataset.id}`;f.title.value=b.dataset.title;f.url.value=b.dataset.url;f.published_at.value=b.dataset.date;f.sort_order.value=b.dataset.order;f.is_active.checked=b.dataset.active==='1'}))</script>@endpush
