<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\HeaderFooterController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\CourseOptionController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\BlogCategoryController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\Admin\CertificationController;
use App\Http\Controllers\CoursePageController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\BlogPageController;
use App\Http\Controllers\Admin\HeroSectionController;
use App\Http\Controllers\Admin\MasterSkillsController;
use App\Http\Controllers\Admin\WhyChooseController;
use App\Http\Controllers\Admin\AchievementStatController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\VideoPageController;
use App\Http\Controllers\MediaPageController;
use App\Http\Controllers\Admin\MediaItemController;
use App\Http\Controllers\AboutPageController;
use App\Http\Controllers\Admin\AboutPageController as AdminAboutPageController;
use App\Http\Controllers\TheoryCoursePageController;
use App\Http\Controllers\Admin\TheoryCourseController;
use App\Http\Controllers\ContactPageController;
use App\Http\Controllers\OfflineEnrollmentController;
use App\Http\Controllers\Admin\ContactPageController as AdminContactPageController;
use App\Http\Controllers\Admin\OfflineEnrollmentController as AdminOfflineEnrollmentController;
use Illuminate\Support\Facades\Artisan;

Route::view('/', 'pages.home')->name('home');
Route::get('/about', AboutPageController::class)->name('about');
Route::view('/corporate', 'pages.corporate')->name('corporate');
Route::view('/login', 'pages.login')->name('login');
Route::view('/register', 'pages.register')->name('register');
Route::get('/courses', CoursePageController::class)->name('courses');
Route::get('/courses/course-details/{course}', [CoursePageController::class, 'show'])->name('courses.show');
Route::get('/enroll/offline-courses', [OfflineEnrollmentController::class, 'create'])->name('offline-enrollments.create');
Route::post('/enroll/offline-courses', [OfflineEnrollmentController::class, 'store'])->name('offline-enrollments.store');
Route::get('/theory-courses', [TheoryCoursePageController::class, 'index'])->name('theory-courses');
Route::get('/theory-courses/details/{theoryCourse}', [TheoryCoursePageController::class, 'show'])->name('theory-courses.show');
Route::view('/online-courses', 'pages.online-courses')->name('online-courses');
Route::view('/books', 'pages.books')->name('books');
Route::get('/blogs', [BlogPageController::class, 'index'])->name('blogs');
Route::get('/blogs/{blog:slug}', [BlogPageController::class, 'show'])->name('blogs.show');
Route::get('/media', [MediaPageController::class, 'index'])->name('media');
Route::get('/video-details/{video}', [VideoPageController::class, 'show'])->name('videos.show');
Route::get('/contact', [ContactPageController::class, 'index'])->name('contact');
Route::post('/contact', [ContactPageController::class, 'store'])->name('contact.store');

Route::prefix('admin')->name('admin.')->group(function () {
    Route::middleware('guest')->group(function () {
        Route::get('/login', [AuthController::class, 'create'])->name('login');
        Route::post('/login', [AuthController::class, 'store'])->name('login.store');
    });

    Route::middleware(['auth', 'super_admin'])->group(function () {
        Route::get('/dashboard', DashboardController::class)->name('dashboard');
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::get('/home/header-footer', [HeaderFooterController::class, 'edit'])->name('home.header-footer.edit');
        Route::put('/home/header-footer', [HeaderFooterController::class, 'update'])->name('home.header-footer.update');
        Route::get('/home/hero', [HeroSectionController::class, 'edit'])->name('home.hero.edit');
        Route::put('/home/hero', [HeroSectionController::class, 'update'])->name('home.hero.update');
        Route::get('/home/master-skills', [MasterSkillsController::class, 'edit'])->name('home.master-skills.edit');
        Route::put('/home/master-skills', [MasterSkillsController::class, 'update'])->name('home.master-skills.update');
        Route::get('/about', [AdminAboutPageController::class, 'edit'])->name('about.edit');
        Route::put('/about', [AdminAboutPageController::class, 'update'])->name('about.update');
        Route::get('/contact', [AdminContactPageController::class, 'edit'])->name('contact.edit');
        Route::put('/contact', [AdminContactPageController::class, 'update'])->name('contact.update');
        Route::get('/messages', [AdminContactPageController::class, 'messages'])->name('contact.messages');
        Route::get('/messages/{message}', [AdminContactPageController::class, 'show'])->name('contact.messages.show');
        Route::delete('/messages/{message}', [AdminContactPageController::class, 'destroy'])->name('contact.messages.destroy');
        Route::get('/home/why-choose', [WhyChooseController::class, 'index'])->name('home.why-choose.index');
        Route::put('/home/why-choose-title', [WhyChooseController::class, 'title'])->name('home.why-choose.title');
        Route::post('/home/why-choose', [WhyChooseController::class, 'store'])->name('home.why-choose.store');
        Route::put('/home/why-choose/{whyChoose}', [WhyChooseController::class, 'update'])->name('home.why-choose.update');
        Route::delete('/home/why-choose/{whyChoose}', [WhyChooseController::class, 'destroy'])->name('home.why-choose.destroy');
        Route::get('/home/achievements', [AchievementStatController::class, 'index'])->name('home.achievements.index');
        Route::put('/home/achievements-title', [AchievementStatController::class, 'title'])->name('home.achievements.title');
        Route::post('/home/achievements', [AchievementStatController::class, 'store'])->name('home.achievements.store');
        Route::put('/home/achievements/{achievement}', [AchievementStatController::class, 'update'])->name('home.achievements.update');
        Route::delete('/home/achievements/{achievement}', [AchievementStatController::class, 'destroy'])->name('home.achievements.destroy');
        Route::get('/home/testimonials', [TestimonialController::class, 'index'])->name('home.testimonials.index');
        Route::put('/home/testimonials-settings', [TestimonialController::class, 'settings'])->name('home.testimonials.settings');
        Route::post('/home/testimonials', [TestimonialController::class, 'store'])->name('home.testimonials.store');
        Route::put('/home/testimonials/{testimonial}', [TestimonialController::class, 'update'])->name('home.testimonials.update');
        Route::delete('/home/testimonials/{testimonial}', [TestimonialController::class, 'destroy'])->name('home.testimonials.destroy');
        Route::get('/courses', [CourseController::class, 'index'])->name('courses.index');
        Route::get('/courses/create', [CourseController::class, 'create'])->name('courses.create');
        Route::post('/courses', [CourseController::class, 'store'])->name('courses.store');
        Route::get('/courses/{course}/edit', [CourseController::class, 'edit'])->name('courses.edit');
        Route::put('/courses/{course}', [CourseController::class, 'update'])->name('courses.update');
        Route::delete('/courses/{course}', [CourseController::class, 'destroy'])->name('courses.destroy');
        Route::get('/enrollments', [AdminOfflineEnrollmentController::class, 'index'])->name('enrollments.index');
        Route::get('/enrollments/{enrollment}', [AdminOfflineEnrollmentController::class, 'show'])->name('enrollments.show');
        Route::put('/enrollments/{enrollment}/status', [AdminOfflineEnrollmentController::class, 'status'])->name('enrollments.status');
        Route::delete('/enrollments/{enrollment}', [AdminOfflineEnrollmentController::class, 'destroy'])->name('enrollments.destroy');
        Route::resource('theory-courses', TheoryCourseController::class)->except('show');
        Route::put('/theory-course-page-settings', [TheoryCourseController::class, 'settings'])->name('theory-courses.settings');
        Route::get('/courses/options/{option}', [CourseOptionController::class, 'index'])->whereIn('option', ['types', 'cities', 'branches'])->name('courses.options.index');
        Route::post('/courses/options/{option}', [CourseOptionController::class, 'store'])->whereIn('option', ['types', 'cities', 'branches'])->name('courses.options.store');
        Route::put('/courses/options/{option}/{id}', [CourseOptionController::class, 'update'])->whereIn('option', ['types', 'cities', 'branches'])->name('courses.options.update');
        Route::delete('/courses/options/{option}/{id}', [CourseOptionController::class, 'destroy'])->whereIn('option', ['types', 'cities', 'branches'])->name('courses.options.destroy');
        Route::resource('blogs', BlogController::class)->except('show');
        Route::post('/blogs/upload', [BlogController::class, 'upload'])->name('blogs.upload');
        Route::get('/blog-categories', [BlogCategoryController::class, 'index'])->name('blog-categories.index');
        Route::post('/blog-categories', [BlogCategoryController::class, 'store'])->name('blog-categories.store');
        Route::put('/blog-categories/{category}', [BlogCategoryController::class, 'update'])->name('blog-categories.update');
        Route::delete('/blog-categories/{category}', [BlogCategoryController::class, 'destroy'])->name('blog-categories.destroy');
        Route::resource('gallery', GalleryController::class)->only(['index', 'store', 'update', 'destroy']);
        Route::put('/gallery-section-settings', [GalleryController::class, 'settings'])->name('gallery.settings');
        Route::resource('media', MediaItemController::class)->only(['index','store','update','destroy']);
        Route::put('/media-page-settings', [MediaItemController::class, 'settings'])->name('media.settings');
        Route::resource('videos', VideoController::class)->only(['index', 'store', 'update', 'destroy']);
        Route::put('/videos-section-settings', [VideoController::class, 'settings'])->name('videos.settings');
        Route::resource('certifications', CertificationController::class)->only(['index', 'store', 'update', 'destroy']);
        Route::put('/certifications-title', [CertificationController::class, 'title'])->name('certifications.title');
        Route::resource('faqs', FaqController::class)->only(['index', 'store', 'update', 'destroy']);
        Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
    });
});

Route::get('/link', function () {
    Artisan::call('storage:link');
    return 'done';
});