@extends('layouts.admin')
@section('title','Gallery')
@section('page_title','Gallery')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center gap-3 mb-4"><div><h1>Gallery</h1><p>Upload and manage website gallery images.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#uploadGallery"><i class="bi bi-cloud-arrow-up me-1"></i> Upload Image</button></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form class="panel settings-panel mb-4" method="POST" action="{{ route('admin.gallery.settings') }}">@csrf @method('PUT')<div class="panel-head"><div><h3>Homepage Gallery Section</h3><p>Update the heading and “See all” link</p></div></div><div class="settings-body row g-3"><div class="col-md-5"><label class="form-label">Section Title</label><input class="form-control" name="gallery_section_title" value="{{ $settings->gallery_section_title ?: 'Image Gallery' }}" required></div><div class="col-md-3"><label class="form-label">Link Text</label><input class="form-control" name="gallery_section_link_text" value="{{ $settings->gallery_section_link_text ?: 'See all' }}" required></div><div class="col-md-4"><label class="form-label">Link URL</label><input class="form-control" name="gallery_section_link_url" value="{{ $settings->gallery_section_link_url ?: '/media' }}" required></div><div class="col-12 text-end"><button class="btn btn-admin-primary">Save Section</button></div></div></form>
<div class="row g-3">@forelse($images as $gallery)<div class="col-12 col-sm-6 col-lg-4 col-xxl-3"><article class="gallery-admin-card"><div class="gallery-admin-image"><img src="{{ asset('storage/'.$gallery->image) }}" alt="{{ $gallery->title?:'Gallery image' }}" loading="lazy"><span class="gallery-status {{ $gallery->is_active?'active':'inactive' }}">{{ $gallery->is_active?'Active':'Inactive' }}</span></div><div class="gallery-admin-body"><div><h3>{{ $gallery->title?:'Untitled Image' }}</h3><small>Order: {{ $gallery->sort_order }}</small></div><div class="d-flex gap-1"><button class="btn btn-sm btn-light border edit-gallery" data-bs-toggle="modal" data-bs-target="#editGallery" data-id="{{ $gallery->id }}" data-title="{{ $gallery->title }}" data-order="{{ $gallery->sort_order }}" data-active="{{ $gallery->is_active?1:0 }}" data-image="{{ asset('storage/'.$gallery->image) }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.gallery.destroy',$gallery) }}" onsubmit="return confirm('Delete this gallery image?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></div></article></div>@empty<div class="col-12"><div class="panel text-center py-5 text-secondary"><i class="bi bi-images fs-1 d-block mb-2"></i>No gallery images uploaded yet.</div></div>@endforelse</div><div class="mt-4">{{ $images->links() }}</div>
@include('admin.gallery.partials.modal',['id'=>'uploadGallery','title'=>'Upload Gallery Image','formId'=>'uploadGalleryForm','action'=>route('admin.gallery.store'),'editing'=>false])
@include('admin.gallery.partials.modal',['id'=>'editGallery','title'=>'Edit Gallery Image','formId'=>'editGalleryForm','action'=>'#','editing'=>true])
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-gallery').forEach(btn=>btn.addEventListener('click',()=>{const f=document.getElementById('editGalleryForm');f.action=`{{ url('/admin/gallery') }}/${btn.dataset.id}`;f.title.value=btn.dataset.title;f.sort_order.value=btn.dataset.order;f.is_active.checked=btn.dataset.active==='1';document.getElementById('editGalleryPreview').src=btn.dataset.image}))</script>@endpush
