@extends('layouts.admin')
@section('title','Achievements')
@section('page_title','Achievements')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center mb-4"><div><h1>Achievement Statistics</h1><p>Manage the homepage goal counters.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#addAchievement"><i class="bi bi-plus-lg"></i> Add Statistic</button></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="panel settings-panel mb-4"><div class="panel-head"><div><h3>Section Heading</h3></div></div><form class="settings-body d-flex flex-column flex-sm-row gap-2" method="POST" action="{{ route('admin.home.achievements.title') }}">@csrf @method('PUT')<input class="form-control" name="achievement_title" value="{{ $sectionTitle }}" required><button class="btn btn-admin-primary flex-shrink-0">Update Title</button></form></div>
<div class="row g-3">@forelse($items as $item)<div class="col-12 col-sm-6 col-xl-4"><article class="panel p-4 h-100 text-center"><i class="{{ $item->icon_class }} mb-2" style="font-size:40px;color:{{ $item->icon_color }}"></i><h2>{{ $item->value }}</h2><p class="text-secondary">{{ $item->label }}</p><small>Order: {{ $item->sort_order }} · <span class="{{ $item->is_active?'text-success':'text-danger' }}">{{ $item->is_active?'Active':'Inactive' }}</span></small><div class="d-flex justify-content-center gap-1 mt-3"><button class="btn btn-sm btn-light border edit-achievement" data-bs-toggle="modal" data-bs-target="#editAchievement" data-id="{{ $item->id }}" data-value="{{ $item->value }}" data-label="{{ $item->label }}" data-icon="{{ $item->icon_class }}" data-color="{{ $item->icon_color }}" data-order="{{ $item->sort_order }}" data-active="{{ $item->is_active?1:0 }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.home.achievements.destroy',$item) }}" onsubmit="return confirm('Delete this statistic?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></article></div>@empty<div class="col-12"><div class="panel text-center py-5 text-secondary">No statistics found.</div></div>@endforelse</div><div class="mt-4">{{ $items->links() }}</div>
@include('admin.home.partials.achievement-modal',['id'=>'addAchievement','title'=>'Add Statistic','formId'=>'addAchievementForm','action'=>route('admin.home.achievements.store'),'editing'=>false])
@include('admin.home.partials.achievement-modal',['id'=>'editAchievement','title'=>'Edit Statistic','formId'=>'editAchievementForm','action'=>'#','editing'=>true])
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-achievement').forEach(b=>b.addEventListener('click',()=>{const f=document.getElementById('editAchievementForm');f.action=`{{ url('/admin/home/achievements') }}/${b.dataset.id}`;f.value.value=b.dataset.value;f.label.value=b.dataset.label;f.icon_class.value=b.dataset.icon;f.icon_color.value=b.dataset.color;f.sort_order.value=b.dataset.order;f.is_active.checked=b.dataset.active==='1'}))</script>@endpush
