@extends('layouts.admin')
@section('title','Certifications')
@section('page_title','Certifications')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center mb-4"><div><h1>Certifications</h1><p>Manage the “Certified By” section on the homepage.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#addCertification"><i class="bi bi-plus-lg"></i> Add Logo</button></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="panel settings-panel mb-4"><div class="panel-head"><div><h3>Section Heading</h3><p>Change the title displayed beside the logos</p></div></div><form class="settings-body d-flex flex-column flex-sm-row gap-2" method="POST" action="{{ route('admin.certifications.title') }}">@csrf @method('PUT')<input class="form-control" name="certification_title" value="{{ $sectionTitle }}" required><button class="btn btn-admin-primary flex-shrink-0">Update Title</button></form></div>
<div class="row g-3">@forelse($certifications as $item)@php($imageUrl=str_starts_with($item->image,'assets/')?asset($item->image):asset('storage/'.$item->image))<div class="col-12 col-sm-6 col-lg-4 col-xxl-3"><article class="certification-admin-card"><div class="certification-logo-preview"><img src="{{ $imageUrl }}" alt="{{ $item->name }}"><span class="gallery-status {{ $item->is_active?'active':'inactive' }}">{{ $item->is_active?'Active':'Inactive' }}</span></div><div class="gallery-admin-body"><div><h3>{{ $item->name }}</h3><small>Order: {{ $item->sort_order }}</small></div><div class="d-flex gap-1"><button class="btn btn-sm btn-light border edit-certification" data-bs-toggle="modal" data-bs-target="#editCertification" data-id="{{ $item->id }}" data-name="{{ $item->name }}" data-order="{{ $item->sort_order }}" data-active="{{ $item->is_active?1:0 }}" data-image="{{ $imageUrl }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.certifications.destroy',$item) }}" onsubmit="return confirm('Delete this certification?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></div></article></div>@empty<div class="col-12"><div class="panel text-center py-5 text-secondary">No certification logos found.</div></div>@endforelse</div><div class="mt-4">{{ $certifications->links() }}</div>
@include('admin.home.partials.certification-modal',['id'=>'addCertification','title'=>'Add Certification','formId'=>'addCertificationForm','action'=>route('admin.certifications.store'),'editing'=>false])
@include('admin.home.partials.certification-modal',['id'=>'editCertification','title'=>'Edit Certification','formId'=>'editCertificationForm','action'=>'#','editing'=>true])
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-certification').forEach(btn=>btn.addEventListener('click',()=>{const f=document.getElementById('editCertificationForm');f.action=`{{ url('/admin/certifications') }}/${btn.dataset.id}`;f.name.value=btn.dataset.name;f.sort_order.value=btn.dataset.order;f.is_active.checked=btn.dataset.active==='1';document.getElementById('editCertificationPreview').src=btn.dataset.image}))</script>@endpush
