@extends('layouts.admin')
@section('title','Hero Section')
@section('page_title','Hero Section')
@section('content')
<div class="page-heading mb-4"><h1>Hero Section</h1><p>Manage the homepage banner, content, badges and statistics.</p></div>@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.home.hero.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="panel settings-panel mb-4"><div class="panel-head"><div><h3>Banner Content</h3><p>Main homepage hero content</p></div></div><div class="settings-body row g-3"><div class="col-12"><label class="form-label">Background Image</label>@if($settings->hero_background)<img class="hero-admin-preview mb-3" src="{{ asset('storage/'.$settings->hero_background) }}" alt="Hero">@endif<input class="form-control" type="file" name="hero_background" accept="image/*"><small class="text-secondary">Recommended 1920×900 · Max 6MB</small></div><div class="col-12"><label class="form-label">Subtitle / Badge</label><input class="form-control" name="hero_subtitle" value="{{ old('hero_subtitle',$settings->hero_subtitle) }}"></div><div class="col-12"><label class="form-label">Main Title</label><input class="form-control" name="hero_title" value="{{ old('hero_title',$settings->hero_title) }}" required></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="hero_description" rows="3">{{ old('hero_description',$settings->hero_description) }}</textarea></div><div class="col-md-3"><label class="form-label">Primary Button</label><input class="form-control" name="hero_primary_text" value="{{ old('hero_primary_text',$settings->hero_primary_text) }}"></div><div class="col-md-3"><label class="form-label">Primary URL</label><input class="form-control" name="hero_primary_url" value="{{ old('hero_primary_url',$settings->hero_primary_url) }}"></div><div class="col-md-3"><label class="form-label">Secondary Button</label><input class="form-control" name="hero_secondary_text" value="{{ old('hero_secondary_text',$settings->hero_secondary_text) }}"></div><div class="col-md-3"><label class="form-label">Secondary URL</label><input class="form-control" name="hero_secondary_url" value="{{ old('hero_secondary_url',$settings->hero_secondary_url) }}"></div><div class="col-md-6"><label class="form-label">Success Story Title</label><input class="form-control" name="hero_success_title" value="{{ old('hero_success_title',$settings->hero_success_title) }}"></div><div class="col-md-6"><label class="form-label">Success Story Text</label><input class="form-control" name="hero_success_text" value="{{ old('hero_success_text',$settings->hero_success_text) }}"></div></div></div>
<div class="panel settings-panel mb-4"><div class="panel-head"><div><h3>Feature Badges</h3><p>Three floating badges displayed on desktop</p></div></div><div class="settings-body row g-3">@foreach(($settings->hero_badges?:array_fill(0,3,['title'=>'','text'=>''])) as $i=>$badge)<div class="col-lg-4"><div class="menu-editor-body border rounded p-3"><strong class="d-block mb-3">Badge {{ $i+1 }}</strong><label class="form-label">Title</label><input class="form-control mb-2" name="hero_badges[{{ $i }}][title]" value="{{ $badge['title']??'' }}"><label class="form-label">Text</label><input class="form-control" name="hero_badges[{{ $i }}][text]" value="{{ $badge['text']??'' }}"></div></div>@endforeach</div></div>
<div class="panel settings-panel mb-4"><div class="panel-head"><div><h3>Statistics</h3><p>Four cards displayed below the hero</p></div></div><div class="settings-body row g-3">@foreach(($settings->hero_stats?:array_fill(0,4,['value'=>'','label'=>''])) as $i=>$stat)<div class="col-md-6 col-xl-3"><label class="form-label">Value {{ $i+1 }}</label><input class="form-control mb-2" name="hero_stats[{{ $i }}][value]" value="{{ $stat['value']??'' }}"><label class="form-label">Label</label><input class="form-control" name="hero_stats[{{ $i }}][label]" value="{{ $stat['label']??'' }}"></div>@endforeach</div></div><div class="sticky-save"><span>Changes appear immediately on the homepage.</span><button class="btn btn-admin-primary px-4">Save Hero</button></div></form>
@endsection
@push('scripts')<style>.hero-admin-preview{display:block;width:100%;max-height:280px;object-fit:cover;border-radius:10px}</style>@endpush
