@extends('layouts.admin')
@section('title','Testimonials') @section('page_title','Testimonials')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center mb-4"><div><h1>Testimonials</h1><p>Manage the homepage review slider.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#addTestimonial"><i class="bi bi-plus-lg"></i> Add Review</button></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form class="panel settings-panel mb-4" method="POST" action="{{ route('admin.home.testimonials.settings') }}" enctype="multipart/form-data">@csrf @method('PUT')<div class="panel-head"><div><h3>Section Settings</h3><p>Heading, button and optional background image</p></div></div><div class="settings-body row g-3"><div class="col-md-6"><label class="form-label">Title</label><input class="form-control" name="testimonial_title" value="{{ $settings->testimonial_title?:'They Trust Us' }}" required></div><div class="col-md-6"><label class="form-label">Subtitle</label><input class="form-control" name="testimonial_subtitle" value="{{ $settings->testimonial_subtitle }}"></div><div class="col-md-4"><label class="form-label">Button Text</label><input class="form-control" name="testimonial_button_text" value="{{ $settings->testimonial_button_text?:'View all Review' }}" required></div><div class="col-md-8"><label class="form-label">Button URL</label><input class="form-control" name="testimonial_button_url" value="{{ $settings->testimonial_button_url }}"></div><div class="col-12"><label class="form-label">Background Image</label><input class="form-control" type="file" name="testimonial_background" accept="image/*"></div><div class="col-12 text-end"><button class="btn btn-admin-primary">Save Settings</button></div></div></form>
<div class="row g-3">@forelse($items as $item)<div class="col-12 col-lg-6"><article class="panel p-3 h-100"><div class="d-flex gap-3">@if($item->photo)<img src="{{ asset('storage/'.$item->photo) }}" class="rounded-circle" style="width:52px;height:52px;object-fit:cover" alt="">@else<div class="rounded-circle bg-light d-flex align-items-center justify-content-center" style="width:52px;height:52px">{{ mb_strtoupper(mb_substr($item->name,0,1)) }}</div>@endif<div class="flex-grow-1"><h3 class="fs-6 mb-1">{{ $item->name }}</h3><div class="text-warning mb-2">{{ str_repeat('★',$item->rating) }}</div><p class="text-secondary small">{{ $item->review }}</p><small>Order: {{ $item->sort_order }} · {{ $item->is_active?'Active':'Inactive' }}</small></div></div><div class="d-flex justify-content-end gap-1"><button class="btn btn-sm btn-light border edit-testimonial" data-bs-toggle="modal" data-bs-target="#editTestimonial" data-id="{{ $item->id }}" data-name="{{ $item->name }}" data-review="{{ $item->review }}" data-rating="{{ $item->rating }}" data-order="{{ $item->sort_order }}" data-active="{{ $item->is_active?1:0 }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.home.testimonials.destroy',$item) }}" onsubmit="return confirm('Delete this review?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></article></div>@empty<div class="col-12"><div class="panel text-center py-5">No reviews found.</div></div>@endforelse</div><div class="mt-4">{{ $items->links() }}</div>
@include('admin.home.partials.testimonial-modal',['id'=>'addTestimonial','title'=>'Add Review','formId'=>'addTestimonialForm','action'=>route('admin.home.testimonials.store'),'editing'=>false])
@include('admin.home.partials.testimonial-modal',['id'=>'editTestimonial','title'=>'Edit Review','formId'=>'editTestimonialForm','action'=>'#','editing'=>true])
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-testimonial').forEach(b=>b.addEventListener('click',()=>{const f=document.getElementById('editTestimonialForm');f.action=`{{ url('/admin/home/testimonials') }}/${b.dataset.id}`;f.name.value=b.dataset.name;f.review.value=b.dataset.review;f.rating.value=b.dataset.rating;f.sort_order.value=b.dataset.order;f.is_active.checked=b.dataset.active==='1'}))</script>@endpush
