@extends('layouts.admin')
@section('title','Blog Categories')
@section('page_title','Blog Categories')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center mb-4"><div><h1>Blog Categories</h1><p>Manage categories for blog posts.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#createCategory"><i class="bi bi-plus-lg"></i> Add Category</button></div>@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="panel"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($categories as $category)<tr><td><strong>{{ $category->name }}</strong></td><td><code>{{ $category->slug }}</code></td><td><span class="status-pill">{{ $category->is_active?'Active':'Inactive' }}</span></td><td class="text-end"><button class="btn btn-sm btn-light border edit-category" data-bs-toggle="modal" data-bs-target="#editCategory" data-id="{{ $category->id }}" data-name="{{ $category->name }}" data-active="{{ $category->is_active?1:0 }}"><i class="bi bi-pencil"></i></button><form class="d-inline" method="POST" action="{{ route('admin.blog-categories.destroy',$category) }}" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="4" class="text-center py-5">No categories.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $categories->links() }}</div>
@foreach([['createCategory','Add Category','createCategoryForm',route('admin.blog-categories.store'),'POST'],['editCategory','Edit Category','editCategoryForm','#','PUT']] as [$id,$title,$formId,$action,$method])<div class="modal fade" id="{{ $id }}"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="{{ $formId }}" method="POST" action="{{ $action }}">@csrf @if($method==='PUT')@method('PUT')@endif<div class="modal-header"><h5>{{ $title }}</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Name</label><input class="form-control" name="name" required><div class="form-check form-switch mt-3"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><label>Active</label></div></div><div class="modal-footer"><button class="btn btn-light border" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-admin-primary">Save</button></div></form></div></div></div>@endforeach
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-category').forEach(b=>b.addEventListener('click',()=>{const f=document.getElementById('editCategoryForm');f.action=`{{ url('/admin/blog-categories') }}/${b.dataset.id}`;f.name.value=b.dataset.name;f.is_active.checked=b.dataset.active==='1'}))</script>@endpush
