@extends('layouts.admin')
@php($editing=$blog->exists)
@section('title',$editing?'Edit Blog':'Create Blog')
@section('page_title',$editing?'Edit Blog':'Create Blog')
@section('content')
<div class="page-heading mb-4"><h1>{{ $editing?'Edit Blog':'Create Blog' }}</h1><p>{{ $editing?'Update your blog post.':'Write and publish a new blog post.' }}</p></div>@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $editing?route('admin.blogs.update',$blog):route('admin.blogs.store') }}" enctype="multipart/form-data">@csrf @if($editing)@method('PUT')@endif<div class="row g-4"><div class="col-xl-8"><div class="panel settings-panel"><div class="panel-head"><div><h3>Blog Content</h3><p>Title, slug and rich description</p></div></div><div class="settings-body row g-3"><div class="col-12"><label class="form-label fw-bold">Title</label><input id="blogTitle" class="form-control" name="title" value="{{ old('title',$blog->title) }}" required></div><div class="col-12"><label class="form-label fw-bold">Slug Preview</label><div class="input-group"><span class="input-group-text">/blogs/</span><input id="blogSlug" class="form-control" value="{{ $blog->slug }}" placeholder="auto-generated" readonly></div><small class="text-secondary">Unique slug is generated automatically.</small></div><div class="col-12"><label class="form-label fw-bold">Description</label><textarea id="blogDescription" name="description">{{ old('description',$blog->description) }}</textarea><small class="text-secondary">Use the image toolbar button to upload images inside the article.</small></div></div></div></div>
<div class="col-xl-4"><div class="panel settings-panel mb-4"><div class="panel-head"><div><h3>Publish Settings</h3></div></div><div class="settings-body"><div class="mb-3"><label class="form-label fw-bold">Category</label><select class="form-select" name="blog_category_id" required><option value="">Select Category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('blog_category_id',$blog->blog_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label fw-bold">Status</label><select class="form-select" name="status" required><option value="draft" @selected(old('status',$blog->status?:'draft')==='draft')>Draft</option><option value="published" @selected(old('status',$blog->status)==='published')>Published</option></select></div><div><label class="form-label fw-bold">Featured Image</label><input class="form-control" type="file" name="image" accept="image/*">@if($blog->image)<img class="img-fluid rounded mt-3" style="max-height:180px;object-fit:cover" src="{{ asset('storage/'.$blog->image) }}" alt="Featured">@endif</div></div></div><div class="d-grid gap-2"><button class="btn btn-admin-primary py-3"><i class="bi bi-check2 me-2"></i>{{ $editing?'Update Blog':'Save Blog' }}</button><a class="btn btn-light border" href="{{ route('admin.blogs.index') }}">Cancel</a></div></div></div></form>
@endsection
@push('scripts')
<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script><script>
const title=document.getElementById('blogTitle'),slug=document.getElementById('blogSlug'),originalTitle=@json($blog->title),originalSlug=@json($blog->slug);function slugify(v){return v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/[\s-]+/g,'-').replace(/^-|-$/g,'')}title.addEventListener('input',()=>slug.value=title.value===originalTitle?originalSlug:slugify(title.value));if(!slug.value)slug.value=slugify(title.value);
class UploadAdapter{constructor(loader){this.loader=loader}upload(){return this.loader.file.then(file=>new Promise((resolve,reject)=>{const data=new FormData;data.append('upload',file);fetch(@json(route('admin.blogs.upload')),{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:data}).then(async r=>{const json=await r.json();if(!r.ok)throw new Error(json.message||'Upload failed');resolve({default:json.url})}).catch(reject)}))}abort(){}}
ClassicEditor.create(document.querySelector('#blogDescription'),{toolbar:['heading','|','bold','italic','link','bulletedList','numberedList','blockQuote','insertTable','uploadImage','undo','redo']}).then(editor=>editor.plugins.get('FileRepository').createUploadAdapter=loader=>new UploadAdapter(loader)).catch(console.error);
</script>@endpush
