@extends('layouts.admin')
@section('title','Enrollment Details') @section('page_title','Enrollment Details')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div class="page-heading"><h1>{{ $enrollment->name }}</h1><p>Application #{{ $enrollment->id }}</p></div><a class="btn btn-light border" href="{{ route('admin.enrollments.index') }}"><i class="bi bi-arrow-left"></i> Back</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
<div class="row g-4"><div class="col-lg-8"><div class="panel"><div class="panel-head"><h3>Student & Course Information</h3></div><div class="settings-body"><div class="row g-4">
@foreach([['Name',$enrollment->name],['Mobile',$enrollment->mobile],['Email',$enrollment->email],['Date of Birth',$enrollment->date_of_birth?->format('d M Y')],['Document',str_replace('_',' ',ucfirst($enrollment->document_type)).': '.$enrollment->document_number],['Address',$enrollment->present_address],['Course',$enrollment->course?->title],['Branch',$enrollment->branch?->name],['Start Date',$enrollment->start_date?->format('d M Y')?:'Not selected'],['Preferred Time',$enrollment->preferred_time?:'Not selected'],['Payment',ucfirst($enrollment->payment_method)],['Payable','BDT '.number_format($enrollment->payable_amount)]] as [$label,$value])<div class="col-md-6"><small class="text-secondary d-block">{{ $label }}</small><strong>{{ $value }}</strong></div>@endforeach
</div><hr><div class="row g-4"><div class="col-md-5"><small class="text-secondary d-block mb-2">Student Photo</small>@if($enrollment->photo)<a class="d-block" target="_blank" href="{{ asset('storage/'.$enrollment->photo) }}"><img src="{{ asset('storage/'.$enrollment->photo) }}" class="img-fluid rounded border bg-light" style="width:100%;max-width:280px;height:230px;object-fit:contain" alt="{{ $enrollment->name }} photo"></a>@else<div class="border rounded bg-light d-flex flex-column align-items-center justify-content-center text-secondary" style="width:100%;max-width:280px;height:230px"><i class="bi bi-person-bounding-box fs-1"></i><span class="mt-2">Photo not uploaded</span></div>@endif</div><div class="col-md-7"><small class="text-secondary d-block mb-2">{{ str_replace('_',' ',ucfirst($enrollment->document_type)) }} Document</small>@if($enrollment->document_path)<a class="d-block" target="_blank" href="{{ asset('storage/'.$enrollment->document_path) }}"><img src="{{ asset('storage/'.$enrollment->document_path) }}" class="img-fluid rounded border bg-light" style="width:100%;max-width:520px;height:300px;object-fit:contain" alt="{{ $enrollment->document_type }} document"></a><a class="btn btn-sm btn-outline-primary mt-2" target="_blank" href="{{ asset('storage/'.$enrollment->document_path) }}"><i class="bi bi-arrows-fullscreen me-1"></i> View Full Image</a>@else<div class="border rounded bg-light d-flex flex-column align-items-center justify-content-center text-secondary" style="height:230px"><i class="bi bi-file-earmark-image fs-1"></i><span class="mt-2">Document not uploaded</span></div>@endif</div></div>
</div></div></div><div class="col-lg-4"><div class="panel"><div class="panel-head"><h3>Update Status</h3></div><div class="settings-body"><form method="POST" action="{{ route('admin.enrollments.status',$enrollment) }}">@csrf @method('PUT')<select class="form-select mb-3" name="status">@foreach(['pending','approved','rejected','completed'] as $status)<option value="{{ $status }}" @selected($enrollment->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn btn-admin-primary w-100">Update Status</button></form></div></div></div></div>
@endsection
