@extends('layouts.admin')
@section('title','About Page') @section('page_title','About Page')
@section('content')
<div class="page-heading mb-4"><h1>About Page</h1><p>Manage all About page-specific content. Features, achievements, certifications and FAQs use their existing admin modules.</p></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.about.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="panel settings-panel mb-4"><div class="panel-head"><h3>Introduction</h3></div><div class="settings-body row g-3"><div class="col-md-6"><label class="form-label">Page Title</label><input class="form-control" name="about_page_title" value="{{ old('about_page_title',$settings->about_page_title?:'About Us') }}" required></div><div class="col-md-6"><label class="form-label">Section Label</label><input class="form-control" name="about_intro_label" value="{{ old('about_intro_label',$settings->about_intro_label?:'Who Are We') }}" required></div><div class="col-12"><label class="form-label">Main Content</label><textarea id="aboutIntroEditor" class="form-control" name="about_intro_content" rows="12">{{ old('about_intro_content',$settings->about_intro_content) }}</textarea></div><div class="col-12"><label class="form-label">Intro YouTube URL</label><input class="form-control" type="url" name="about_intro_video" value="{{ old('about_intro_video',$settings->about_intro_video) }}"></div></div></div>
<div class="panel settings-panel mb-4"><div class="panel-head"><h3>Director's Speech</h3></div><div class="settings-body row g-3"><div class="col-md-6"><label class="form-label">Title</label><input class="form-control" name="about_director_title" value="{{ old('about_director_title',$settings->about_director_title?:"Executive Director's Speech") }}" required></div><div class="col-md-3"><label class="form-label">Name</label><input class="form-control" name="about_director_name" value="{{ old('about_director_name',$settings->about_director_name) }}"></div><div class="col-md-3"><label class="form-label">Designation</label><input class="form-control" name="about_director_designation" value="{{ old('about_director_designation',$settings->about_director_designation) }}"></div><div class="col-12"><label class="form-label">Speech</label><textarea id="directorEditor" class="form-control" name="about_director_content" rows="8">{{ old('about_director_content',$settings->about_director_content) }}</textarea></div><div class="col-12"><label class="form-label">Director Image</label><input class="form-control" type="file" name="about_director_image" accept="image/*"></div></div></div>
<div class="panel settings-panel mb-4"><div class="panel-head"><h3>Feature Section</h3></div><div class="settings-body row g-3"><div class="col-md-4"><label class="form-label">Small Label</label><input class="form-control" name="about_features_label" value="{{ old('about_features_label',$settings->about_features_label?:'Our Features') }}" required></div><div class="col-md-8"><label class="form-label">Title</label><input class="form-control" name="about_features_title" value="{{ old('about_features_title',$settings->about_features_title?:'Why Choose Pathway Driving Training School?') }}" required></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="about_features_description" rows="4">{{ old('about_features_description',$settings->about_features_description) }}</textarea></div><div class="col-12"><label class="form-label">Model Image</label><input class="form-control" type="file" name="about_features_image" accept="image/*"></div></div></div>
<div class="panel settings-panel mb-4"><div class="panel-head"><h3>Training, Certification & FAQ</h3></div><div class="settings-body row g-3"><div class="col-md-6"><label class="form-label">Training Title</label><input class="form-control" name="about_training_title" value="{{ old('about_training_title',$settings->about_training_title?:'Our Training Process') }}" required></div><div class="col-md-6"><label class="form-label">Training YouTube URL</label><input class="form-control" type="url" name="about_training_video" value="{{ old('about_training_video',$settings->about_training_video) }}"></div><div class="col-12"><label class="form-label">Training Background</label><div class="mb-3"><img id="trainingBackgroundPreview" src="{{ $settings->about_training_background?asset('storage/'.$settings->about_training_background):asset('assets/frontend/img/section-bg/video.jpg') }}" alt="Training background" class="img-fluid rounded border" style="width:100%;max-width:520px;height:180px;object-fit:cover"></div><input id="trainingBackgroundInput" class="form-control" type="file" name="about_training_background" accept="image/jpeg,image/png,image/webp"><small class="text-secondary">JPG, PNG or WEBP · Max 10MB. Select the image, then click Save About Page.</small></div><div class="col-md-6"><label class="form-label">Certification Title</label><input class="form-control" name="about_certification_title" value="{{ old('about_certification_title',$settings->about_certification_title?:'We Are Certified By') }}" required></div><div class="col-md-6"><label class="form-label">FAQ Title</label><input class="form-control" name="about_faq_title" value="{{ old('about_faq_title',$settings->about_faq_title?:'Frequently Asked Questions') }}" required></div><div class="col-md-6"><label class="form-label">FAQ Car Image</label><input class="form-control" type="file" name="about_faq_car_image" accept="image/*"></div><div class="col-md-6"><label class="form-label">FAQ Bike Image</label><input class="form-control" type="file" name="about_faq_bike_image" accept="image/*"></div></div></div>
<div class="text-end mb-5"><button class="btn btn-admin-primary px-5 py-3">Save About Page</button></div></form>
@endsection
@push('scripts')<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script><script>['#aboutIntroEditor','#directorEditor'].forEach(selector=>ClassicEditor.create(document.querySelector(selector),{toolbar:['heading','|','bold','italic','link','bulletedList','numberedList','blockQuote','undo','redo']}).catch(console.error));document.getElementById('trainingBackgroundInput')?.addEventListener('change',event=>{const file=event.target.files[0];if(file)document.getElementById('trainingBackgroundPreview').src=URL.createObjectURL(file)})</script>@endpush
