@extends('layouts.admin')
@section('title', 'Profile')
@section('page_title', 'My Profile')
@section('content')
<div class="page-heading mb-4"><h1>Profile Settings</h1><p>Update your personal information and account security.</p></div>
@if(session('status'))<div class="alert alert-success"><i class="bi bi-check-circle me-2"></i>{{ session('status') }}</div>@endif
<form method="POST" action="{{ route('admin.profile.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="row g-4">
    <div class="col-lg-4"><div class="panel profile-photo-card text-center"><div class="profile-photo-preview">@if($user->photo)<img id="photoPreview" src="{{ asset('storage/'.$user->photo) }}" alt="Profile">@else<span id="photoFallback">{{ strtoupper(substr($user->name,0,1)) }}</span><img id="photoPreview" class="d-none" alt="Profile">@endif</div><h3>{{ $user->name }}</h3><p>Super Administrator</p><label class="btn btn-admin-outline" for="photo"><i class="bi bi-camera me-2"></i>Change photo</label><input class="d-none" type="file" name="photo" id="photo" accept="image/*"><small>JPG, PNG or WEBP. Max 2MB.</small>@error('photo')<div class="text-danger small mt-2">{{ $message }}</div>@enderror</div></div>
    <div class="col-lg-8"><div class="panel profile-form"><div class="panel-head"><div><h3>Personal Information</h3><p>Edit your name, email and password</p></div></div><div class="row g-3"><div class="col-12"><label class="form-label">Full name</label><input class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$user->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label">Email address</label><input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email',$user->email) }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><hr><h4>Change Password</h4><p class="text-secondary small">Leave these fields blank to keep the current password.</p><div class="row g-3"><div class="col-12"><label class="form-label">Current password</label><input type="password" class="form-control @error('current_password') is-invalid @enderror" name="current_password">@error('current_password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">New password</label><input type="password" class="form-control @error('password') is-invalid @enderror" name="password">@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Confirm password</label><input type="password" class="form-control" name="password_confirmation"></div></div><div class="d-flex justify-content-end mt-4"><button class="btn btn-admin-primary px-4" type="submit"><i class="bi bi-check2 me-2"></i>Save Changes</button></div></div></div>
</div></form>
@push('scripts')<script>document.getElementById('photo')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const img=document.getElementById('photoPreview');img.src=URL.createObjectURL(f);img.classList.remove('d-none');document.getElementById('photoFallback')?.classList.add('d-none')})</script>@endpush
@endsection
