@extends('layouts.admin')
@section('title','Videos')
@section('page_title','Videos')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center gap-3 mb-4"><div><h1>Videos</h1><p>Manage YouTube videos displayed on the website.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#addVideo"><i class="bi bi-plus-lg me-1"></i>Add Video</button></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form class="panel settings-panel mb-4" method="POST" action="{{ route('admin.videos.settings') }}">@csrf @method('PUT')<div class="panel-head"><div><h3>Homepage Video Section</h3><p>Update the section heading and “See all” link</p></div></div><div class="settings-body row g-3"><div class="col-md-5"><label class="form-label">Section Title</label><input class="form-control" name="video_section_title" value="{{ $settings->video_section_title ?: 'Latest Video Sections' }}" required></div><div class="col-md-3"><label class="form-label">Link Text</label><input class="form-control" name="video_section_link_text" value="{{ $settings->video_section_link_text ?: 'See all' }}" required></div><div class="col-md-4"><label class="form-label">Link URL</label><input class="form-control" name="video_section_link_url" value="{{ $settings->video_section_link_url ?: '/media' }}" required></div><div class="col-12 text-end"><button class="btn btn-admin-primary">Save Section</button></div></div></form>
<div class="row g-3">@forelse($videos as $video)<div class="col-12 col-sm-6 col-lg-4 col-xxl-3"><article class="gallery-admin-card"><a class="gallery-admin-image d-block" href="{{ $video->youtube_url }}" target="_blank" rel="noopener">@if($video->thumbnail)<img src="{{ $video->thumbnail }}" alt="{{ $video->title }}" loading="lazy">@else<div class="w-100 h-100 d-grid place-items-center"><i class="bi bi-play-btn fs-1"></i></div>@endif<span class="video-play-icon"><i class="bi bi-play-fill"></i></span><span class="gallery-status {{ $video->is_active?'active':'inactive' }}">{{ $video->is_active?'Active':'Inactive' }}</span></a><div class="gallery-admin-body"><div><h3>{{ $video->title }}</h3>@if($video->description)<p class="video-card-description">{{ strip_tags($video->description) }}</p>@endif<small>Order: {{ $video->sort_order }}</small></div><div class="d-flex gap-1"><button class="btn btn-sm btn-light border edit-video" data-bs-toggle="modal" data-bs-target="#editVideo" data-id="{{ $video->id }}" data-title="{{ $video->title }}" data-url="{{ $video->youtube_url }}" data-description="{{ $video->description }}" data-order="{{ $video->sort_order }}" data-active="{{ $video->is_active?1:0 }}" data-image="{{ $video->thumbnail }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.videos.destroy',$video) }}" onsubmit="return confirm('Delete this video?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></div></article></div>@empty<div class="col-12"><div class="panel text-center py-5 text-secondary"><i class="bi bi-play-btn fs-1 d-block mb-2"></i>No videos added yet.</div></div>@endforelse</div><div class="mt-4">{{ $videos->links() }}</div>
@include('admin.videos.partials.modal',['id'=>'addVideo','title'=>'Add Video','formId'=>'addVideoForm','action'=>route('admin.videos.store'),'editing'=>false])
@include('admin.videos.partials.modal',['id'=>'editVideo','title'=>'Edit Video','formId'=>'editVideoForm','action'=>'#','editing'=>true])
@endsection
@push('scripts')
<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
<script>
const videoEditors={};
Promise.all([['add',document.querySelector('#addVideoDescription')],['edit',document.querySelector('#editVideoDescription')]].map(([key,element])=>ClassicEditor.create(element,{toolbar:['heading','|','bold','italic','link','bulletedList','numberedList','blockQuote','undo','redo']}).then(editor=>videoEditors[key]=editor))).catch(console.error);
document.querySelectorAll('.edit-video').forEach(btn=>btn.addEventListener('click',()=>{const f=document.getElementById('editVideoForm');f.action=`{{ url('/admin/videos') }}/${btn.dataset.id}`;f.title.value=btn.dataset.title;f.youtube_url.value=btn.dataset.url;videoEditors.edit?.setData(btn.dataset.description||'');f.sort_order.value=btn.dataset.order;f.is_active.checked=btn.dataset.active==='1';const img=document.getElementById('editVideoPreview');if(btn.dataset.image){img.src=btn.dataset.image;img.classList.remove('d-none')}else img.classList.add('d-none')}));
</script>
@endpush
