<?php
namespace App\Http\Controllers;
use App\Models\{Branch,Course,OfflineEnrollment};use Illuminate\Http\{RedirectResponse,Request};use Illuminate\Support\Facades\Hash;use Illuminate\View\View;
class OfflineEnrollmentController extends Controller{
 public function create(Request $r):View{$courses=Course::where('is_active',true)->with('branch')->orderBy('title')->get();$course=$courses->firstWhere('id',(int)$r->integer('course_id'))??$courses->first();return view('pages.offline-enrollment',['courses'=>$courses,'course'=>$course,'branches'=>Branch::where('is_active',true)->orderBy('name')->get()]);}
 public function store(Request $r):RedirectResponse{
  $documentRule=$r->input('document_type')==='birth_certificate'?'regex:/^\d{17}$/':'regex:/^(?:\d{10}|\d{13}|\d{17})$/';
  $data=$r->validate(['name'=>['required','string','min:3','max:255'],'mobile'=>['required','regex:/^(?:\+?88)?01[3-9]\d{8}$/'],'document_type'=>['required','in:nid,birth_certificate'],'document_number'=>['required',$documentRule],'document_path'=>['required','image','mimes:jpg,jpeg,png,webp','max:4096'],'email'=>['required','email:rfc','max:255'],'date_of_birth'=>['required','date','before_or_equal:'.now()->subYears(16)->toDateString()],'present_address'=>['required','string','min:10','max:1000'],'password'=>['required','string','min:8','confirmed'],'photo'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:2048'],'course_id'=>['required','exists:courses,id'],'branch_id'=>['required','exists:branches,id'],'start_date'=>['required','date','after_or_equal:today'],'preferred_time'=>['required','string','max:100'],'payment_method'=>['required','in:office,online'],'coupon_code'=>['nullable','string','max:50']],['document_number.regex'=>'NID must be 10, 13 or 17 digits; Birth Certificate must be 17 digits.','date_of_birth.before_or_equal'=>'Student must be at least 16 years old.']);
  $course=Course::where('is_active',true)->findOrFail($data['course_id']);if((int)$course->branch_id!==(int)$data['branch_id'])return back()->withErrors(['branch_id'=>'Selected branch is not available for this course.'])->withInput();$data['document_path']=$r->file('document_path')->store('enrollments/documents','public');if($r->hasFile('photo'))$data['photo']=$r->file('photo')->store('enrollments/photos','public');$data['password']=Hash::make($data['password']);$data['payable_amount']=$course->fee;unset($data['password_confirmation']);OfflineEnrollment::create($data);return redirect()->route('offline-enrollments.create',['course_id'=>$course->id])->with('status','Your enrollment request has been submitted successfully.');
 }
}
