@extends('layouts.admin')
@section('title','FAQs')
@section('page_title','FAQs')
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center mb-4"><div><h1>Frequently Asked Questions</h1><p>Manage questions shown on the courses page.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#addFaq"><i class="bi bi-plus-lg"></i> Add FAQ</button></div>@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="panel"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Question</th><th>Answer</th><th>Order</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($faqs as $faq)<tr><td><strong>{{ $faq->question }}</strong></td><td style="max-width:400px;white-space:normal">{{ str($faq->answer)->limit(120) }}</td><td>{{ $faq->sort_order }}</td><td><span class="status-pill">{{ $faq->is_active?'Active':'Inactive' }}</span></td><td class="text-end"><button class="btn btn-sm btn-light border edit-faq" data-bs-toggle="modal" data-bs-target="#editFaq" data-id="{{ $faq->id }}" data-question="{{ $faq->question }}" data-answer="{{ $faq->answer }}" data-order="{{ $faq->sort_order }}" data-active="{{ $faq->is_active?1:0 }}"><i class="bi bi-pencil"></i></button><form class="d-inline" method="POST" action="{{ route('admin.faqs.destroy',$faq) }}" onsubmit="return confirm('Delete this FAQ?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center py-5">No FAQs found.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $faqs->links() }}</div>
@include('admin.faqs.partials.modal',['id'=>'addFaq','title'=>'Add FAQ','formId'=>'addFaqForm','action'=>route('admin.faqs.store'),'editing'=>false])
@include('admin.faqs.partials.modal',['id'=>'editFaq','title'=>'Edit FAQ','formId'=>'editFaqForm','action'=>'#','editing'=>true])
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-faq').forEach(btn=>btn.addEventListener('click',()=>{const f=document.getElementById('editFaqForm');f.action=`{{ url('/admin/faqs') }}/${btn.dataset.id}`;f.question.value=btn.dataset.question;f.answer.value=btn.dataset.answer;f.sort_order.value=btn.dataset.order;f.is_active.checked=btn.dataset.active==='1'}))</script>@endpush
