@extends('layouts.admin')
@section('title',$title)
@section('page_title',$title)
@section('content')
<div class="page-heading d-flex justify-content-between align-items-center mb-4"><div><h1>{{ $title }}</h1><p>Manage {{ strtolower($title) }} records used by courses.</p></div><button class="btn btn-admin-primary" data-bs-toggle="modal" data-bs-target="#createModal"><i class="bi bi-plus-lg me-1"></i>Add {{ $title }}</button></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="panel"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>Name</th>@if($option==='branches')<th>City</th><th>Address</th>@endif<th>Status</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ $items->firstItem()+$loop->index }}</td><td><strong>{{ $item->name }}</strong></td>@if($option==='branches')<td>{{ $item->city->name }}</td><td>{{ $item->address ?: '—' }}</td>@endif<td><span class="status-pill">{{ $item->is_active?'Active':'Inactive' }}</span></td><td class="text-end"><button class="btn btn-sm btn-light border edit-option" data-bs-toggle="modal" data-bs-target="#editModal" data-id="{{ $item->id }}" data-name="{{ $item->name }}" data-active="{{ $item->is_active?1:0 }}" @if($option==='branches') data-city="{{ $item->city_id }}" data-address="{{ $item->address }}" @endif><i class="bi bi-pencil"></i></button><form class="d-inline" method="POST" action="{{ route('admin.courses.options.destroy',[$option,$item]) }}" onsubmit="return confirm('Delete this item?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-secondary">No records found.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $items->links() }}</div>
@include('admin.courses.partials.option-modal',['modalId'=>'createModal','modalTitle'=>'Add '.$title,'formId'=>'createForm','action'=>route('admin.courses.options.store',$option),'method'=>'POST'])
@include('admin.courses.partials.option-modal',['modalId'=>'editModal','modalTitle'=>'Edit '.$title,'formId'=>'editForm','action'=>'#','method'=>'PUT'])
@endsection
@push('scripts')<script>document.querySelectorAll('.edit-option').forEach(btn=>btn.addEventListener('click',()=>{const form=document.getElementById('editForm');form.action=`{{ url('/admin/courses/options/'.$option) }}/${btn.dataset.id}`;form.querySelector('[name=name]').value=btn.dataset.name;form.querySelector('[name=is_active]').checked=btn.dataset.active==='1';if(btn.dataset.city)form.querySelector('[name=city_id]').value=btn.dataset.city;if(btn.dataset.address!==undefined)form.querySelector('[name=address]').value=btn.dataset.address}))</script>@endpush
