@extends('layouts.app')
@section('title', $settings?->about_page_title ?: 'About Us')
@section('page_styles')
<style>
.about-features-exact{padding:76px 0 0;background:#fff;overflow:hidden}.about-features-exact .feature-copy{padding-bottom:70px}.about-features-exact .section-sub-head span{display:block;color:#ff6570;font-size:18px;font-weight:700;margin-bottom:22px}.about-features-exact .section-sub-head h2{max-width:610px;color:#0a0a0a;font-size:38px;line-height:1.15;font-weight:700;margin:0 0 22px}.about-features-exact .feature-description{max-width:700px;color:#685f78;font-size:16px;line-height:1.65;margin:0}.about-feature-grid{margin-top:58px}.about-feature-card{width:100%;min-height:138px;border:1px solid #e1e4e8;border-radius:20px;background:#fff;padding:24px;display:grid;grid-template-columns:minmax(115px,.9fr) minmax(130px,1.1fr);align-items:center;gap:18px;margin-bottom:24px;transition:.25s}.about-feature-card:hover{transform:translateY(-5px);box-shadow:0 12px 30px rgba(25,49,96,.08)}.about-feature-card h4{font-size:25px;line-height:1.18;color:#00245d;margin:0;font-weight:500}.about-feature-card p{font-size:14px;line-height:1.6;color:#685f78;margin:0;font-weight:500}.about-features-exact .feature-model{height:100%;display:flex;align-items:flex-end;justify-content:center}.about-features-exact .feature-model img{display:block;width:auto;max-width:100%;max-height:890px;object-fit:contain;object-position:center bottom}
.about-director-exact{padding:72px 0;background:linear-gradient(110deg,#f1fbff 0%,#fbfdff 50%,#ffefec 100%)}.about-director-exact .director-photo{display:block;width:100%;max-width:370px;aspect-ratio:1/1;object-fit:cover;margin:auto}.about-director-exact h2{font-size:34px;line-height:1.2;margin-bottom:25px}.about-director-exact .director-copy{color:#685f78;font-size:16px;line-height:1.6}.about-director-exact .course-list{margin-top:22px}.about-funfacts{background:rgba(250,252,253,.88) url('{{ asset('assets/img/bg-banner-02.png') }}') center/cover no-repeat}.about-training-process{background-position:center!important;background-size:cover!important}
@media(max-width:991.98px){.about-features-exact{padding-top:55px}.about-features-exact .feature-copy{padding-bottom:35px}.about-features-exact .feature-model{display:flex!important;max-height:620px}.about-features-exact .feature-model img{max-height:620px}.about-features-exact .section-sub-head h2{font-size:34px}.about-feature-grid{margin-top:38px}}
@media(max-width:575.98px){.about-features-exact{padding-top:42px}.about-features-exact .section-sub-head h2{font-size:29px}.about-feature-card{min-height:auto;grid-template-columns:1fr;padding:20px;gap:10px}.about-feature-card h4{font-size:22px}.about-feature-grid{margin-top:30px}.about-features-exact .feature-model img{max-height:480px}}
</style>
@endsection
@php
$youtubeId=function($url){preg_match('~(?:youtu\.be/|youtube\.com/(?:watch\?v=|embed/|shorts/))([A-Za-z0-9_-]{11})~',(string)$url,$m);return $m[1]??null;};
$introVideoId=$youtubeId($settings?->about_intro_video);
@endphp
@section('content')
<div class="breadcrumb-bar breadcrumb-bar-info pt-5"><div class="container py-5"><div class="breadcrumb-list text-center"><h2 class="breadcrumb-title">{{ $settings?->about_page_title ?: 'About Us' }}</h2><nav><ol class="breadcrumb justify-content-center"><li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li><li class="breadcrumb-item active">{{ $settings?->about_page_title ?: 'About Us' }}</li></ol></nav></div></div></div>

<section class="section new-course"><div class="container"><div class="section-header" data-aos="fade-up"><div class="section-sub-head"><span>{{ $settings?->about_intro_label ?: 'Who Are We' }}</span></div></div><div class="row g-4"><div class="{{ $introVideoId?'col-lg-9':'col-12' }}"><div class="join-mentor about-rich-content" data-aos="fade-up">{!! $settings?->about_intro_content !!}</div></div>@if($introVideoId)<div class="col-lg-3 d-flex align-items-center"><div class="ratio ratio-16x9 w-100"><iframe src="https://www.youtube.com/embed/{{ $introVideoId }}" title="About Pathway" allowfullscreen></iframe></div></div>@endif</div></div></section>

<section class="about-director-exact"><div class="container"><div class="row g-5 align-items-start"><div class="col-md-6"><img src="{{ $settings?->about_director_image?asset('storage/'.$settings->about_director_image):'https://www.pdts.com.bd/assets/frontend/img/about/director.jpeg' }}" alt="{{ $settings?->about_director_name }}" class="director-photo" data-aos="fade-up"></div><div class="col-md-6"><div class="join-mentor" data-aos="fade-up"><h2>{{ $settings?->about_director_title ?: "Executive Director's Speech" }}</h2><div class="director-copy">{!! $settings?->about_director_content !!}</div><ul class="course-list">@if($settings?->about_director_name)<li><i class="fa-solid fa-circle-check"></i>{{ $settings->about_director_name }}</li>@endif @if($settings?->about_director_designation)<li><i class="fa-solid fa-circle-check"></i>{{ $settings->about_director_designation }}</li>@endif</ul></div></div></div></div></section>

<section class="about-features-exact"><div class="container"><div class="row gx-xl-5 align-items-stretch"><div class="col-lg-7 feature-copy"><div class="section-sub-head" data-aos="fade-up"><span>{{ $settings?->about_features_label ?: 'Our Features' }}</span><h2>{{ $settings?->about_features_title ?: 'Why Choose Pathway Driving Training School?' }}</h2></div><p class="feature-description" data-aos="fade-up">{{ $settings?->about_features_description }}</p><div class="about-feature-grid"><div class="row g-0 gx-md-4">@foreach($features as $feature)<div class="col-md-6 d-flex"><article class="about-feature-card"><h4>{{ $feature->title }}</h4><p>{{ $feature->description }}</p></article></div>@endforeach</div></div></div><div class="col-lg-5 align-self-stretch"><div class="feature-model" data-aos="fade-up"><img src="{{ $settings?->about_features_image?asset('storage/'.$settings->about_features_image):'https://www.pdts.com.bd/assets/img/about-model.png' }}" alt="{{ $settings?->about_features_title }}"></div></div></div></div></section>

<div class="funfact-area about-funfacts overlay overlay-white overlay-80 pt-90 pb-60"><div class="container"><div class="row justify-content-center">@foreach($stats as $stat)<div class="single-facts text-center col-lg col-md-3 col-sm-6 col-12 mb-30"><i class="{{ $stat->icon_class }}" style="font-size:42px;color:{{ $stat->icon_color }}"></i><div class="course-content-three"><h4 class="text-blue"><span class="counterUp">{{ $stat->value }}</span></h4><p>{{ $stat->label }}</p></div></div>@endforeach</div></div></div>

<div class="video-area about-training-process overlay overlay-black overlay-50" @if($settings?->about_training_background) style="background-image:url('{{ asset('storage/'.$settings->about_training_background) }}')" @endif><div class="container"><div class="row"><div class="video-content text-center col-12">@if($settings?->about_training_video)<a class="video-popup" href="{{ $settings->about_training_video }}"><i class="fas fa-play site-text-primary-hov"></i></a>@endif<h3>{{ $settings?->about_training_title ?: 'Our Training Process' }}</h3></div></div></div></div>

<div class="certification-area overlay overlay-white overlay-90 pt-60 pb-60"><div class="container"><div class="row"><div class="section-title text-center col-12 mb-45"><h2 class="mb-3 heading">{{ $settings?->about_certification_title ?: 'We Are Certified By' }}</h2><i class="fas fa-traffic-light site-text-primary"></i></div></div><div class="row certification-row justify-content-center">@foreach($certifications as $certification)@php($image=str_starts_with($certification->image,'assets/')?asset($certification->image):asset('storage/'.$certification->image))<div class="single-cert text-center col-md-3 col-sm-6 col-12 mb-30"><img class="certificate-logo" src="{{ $image }}" alt="{{ $certification->name }}" style="width:180px"><h5 class="mt-3">{{ $certification->name }}</h5></div>@endforeach</div></div></div>

<div id="faq-area" class="faq-area bg-white pt-90 pb-60"><div class="container"><div class="row"><div class="section-title text-center col-12 mb-45"><h2 class="mb-3 heading">{{ $settings?->about_faq_title ?: 'Frequently Asked Questions' }}</h2><i class="fas fa-traffic-light site-text-primary"></i></div></div><div class="row align-items-center"><div class="col-lg-6"><div class="panel-group" id="aboutFaq">@foreach($faqs as $faq)<div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-bs-toggle="collapse" aria-expanded="{{ $loop->first?'true':'false' }}" href="#about-faq-{{ $faq->id }}">{{ $faq->question }}</a></h4></div><div id="about-faq-{{ $faq->id }}" class="panel-collapse collapse {{ $loop->first?'show':'' }}" data-bs-parent="#aboutFaq"><div class="panel-body"><p>{{ $faq->answer }}</p></div></div></div>@endforeach</div></div><div class="faq-image col-lg-4 col-7"><img src="{{ $settings?->about_faq_car_image?asset('storage/'.$settings->about_faq_car_image):asset('assets/frontend/img/faq/car-01.jpg') }}" alt="Car" class="img-fluid"></div><div class="faq-image col-lg-2 col-5"><img src="{{ $settings?->about_faq_bike_image?asset('storage/'.$settings->about_faq_bike_image):asset('assets/frontend/img/faq/bike-01.jpg') }}" alt="Bike" class="img-fluid"></div></div></div></div>
@endsection
