@extends('layouts.app')
@section('title',$settings?->page_title?:'Contact With Us')
@section('page_styles')
<style>
.contact-branch-grid{row-gap:32px}.contact-branch-card{display:block!important;width:100%!important;min-height:270px;padding:38px 28px!important;border:1px solid #e7e7e7;border-radius:10px!important;background:#fff;text-align:center;position:relative;transition:.25s}.contact-branch-card::before{display:none!important}.contact-branch-card:hover{transform:translateY(-4px);box-shadow:0 10px 30px rgba(10,36,93,.08)}.contact-branch-card h3{color:#00245d;font-size:28px;margin:0 0 20px}.contact-branch-card p{max-width:430px;margin:0 auto 10px!important;color:#111;line-height:1.55;overflow-wrap:anywhere}.contact-branch-card a{color:inherit;text-decoration:none}.contact-branch-card strong{font-weight:700}.office-time-section .excerpt{line-height:1.8}.office-time-section .excerpt br{display:block;content:"";margin-top:7px}
@media(max-width:767.98px){.contact-branch-card{min-height:auto;padding:28px 20px!important}.contact-branch-card h3{font-size:24px}}
</style>
@endsection
@section('content')
<div class="breadcrumb-bar breadcrumb-bar-info pt-5"><div class="container py-5"><div class="breadcrumb-list text-center"><h2 class="breadcrumb-title">{{ $settings?->page_title?:'Contact With Us' }}</h2><nav><ol class="breadcrumb justify-content-center"><li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li><li class="breadcrumb-item active">Contact</li></ol></nav></div></div></div>
<section class="branches-area feature-area bg-gray pt-70 pb-90"><div class="container"><div class="text-center mb-5 office-time-section"><h2 class="mb-3 heading">{{ $settings?->office_title?:'Office Time' }}</h2><div class="excerpt">{!! nl2br(e($settings?->office_description)) !!}</div><i class="fas fa-traffic-light site-text-primary"></i></div><div class="text-center mb-45"><h2 class="mb-3 heading">{{ $settings?->branches_title?:'Our Branches' }}</h2><p>{{ $settings?->branches_description }}</p><i class="fas fa-traffic-light site-text-primary"></i></div><div class="row contact-branch-grid justify-content-center">@foreach($branches as $branch)<div class="col-xl-4 col-lg-5 col-md-6 d-flex"><article class="contact-branch-card h-100"><h3>{{ $branch->name }}</h3>@if($branch->phone)<p><strong>Tel:</strong> <a href="tel:{{ $branch->phone }}">{{ $branch->phone }}</a></p>@endif @if($branch->email)<p><strong>Email:</strong> <a href="mailto:{{ $branch->email }}">{{ $branch->email }}</a></p>@endif<p><strong>Address:</strong> {{ $branch->address }}</p></article></div>@endforeach</div></div></section>
<section class="contact-area overlay overlay-white overlay-90 pt-60 pb-60"><div class="container"><div class="section-title text-center mb-45"><h2>{{ $settings?->form_title?:'Get In Touch' }}</h2><p>{{ $settings?->form_description }}</p><i class="fas fa-traffic-light site-text-primary"></i></div>@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif @if($settings?->call_number)<div class="text-center mb-4"><a href="tel:{{ $settings->call_number }}" class="btn site-bg-primary site-bg-secondary-hov fs-5"><i class="fas fa-phone-volume me-2"></i>{{ $settings?->call_button_text?:'Call Now' }}</a></div>@endif<form action="{{ route('contact.store') }}" method="POST" class="contact-form row g-3 mx-auto" style="max-width:950px">@csrf<div class="col-12"><input class="form-control" name="name" value="{{ old('name') }}" placeholder="Name" required></div><div class="col-md-6"><input class="form-control" type="email" name="email" value="{{ old('email') }}" placeholder="Email" required></div><div class="col-md-6"><input class="form-control" name="phone" value="{{ old('phone') }}" placeholder="Mobile Number" required></div><div class="col-12"><input class="form-control" name="subject" value="{{ old('subject') }}" placeholder="Subject" required></div><div class="col-12"><textarea class="form-control" name="message" rows="7" placeholder="Write Your Message Here" required>{{ old('message') }}</textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="agreement" value="1" id="agreement" required><label class="form-check-label" for="agreement">{{ $settings?->agreement_text?:'I agree with the' }} <a href="{{ url($settings?->terms_url?:'/terms-and-conditions') }}">Terms of Use</a> and <a href="{{ url($settings?->privacy_url?:'/privacy-policy') }}">Privacy Policy</a>.</label></div></div><div class="col-12 text-end"><button class="btn site-bg-primary site-bg-secondary-hov">{{ $settings?->submit_button_text?:'Send Message' }}</button></div></form></div></section>
@if($settings?->map_embed_url)<section><div class="section-title text-center pt-5 mb-4"><h2>{{ $settings?->map_title?:'Locate Us on Google Map' }}</h2><i class="fas fa-traffic-light site-text-primary"></i></div><iframe src="{{ $settings->map_embed_url }}" width="100%" height="450" style="border:0" allowfullscreen loading="lazy"></iframe></section>@endif
@endsection
