@extends('layouts.app')
@section('title',$course->title)
@section('page_styles')<style>.course-hero{background:linear-gradient(90deg,rgba(3,20,48,.92),rgba(3,20,48,.65)),url('{{ $course->image?asset('storage/'.$course->image):asset('assets/img/bg-banner-02.png') }}') center/cover;padding:55px 0;color:#fff}.detail-card{background:#fff;border:1px solid #e5e9ef;border-radius:10px;padding:24px;box-shadow:0 5px 18px rgba(0,0,0,.05)}.detail-cover{height:210px;object-fit:cover}.related-cover{height:210px;object-fit:cover}.detail-description img{max-width:100%;height:auto}.branch-address{overflow-wrap:anywhere}@media(max-width:767px){.course-hero{padding:35px 0}.detail-cover{height:auto}}</style>@endsection
@section('content')
<div class="breadcrumb-bar breadcrumb-bar-info pt-5"><div class="container py-4 text-center"><h2>{{ $course->title }}</h2><ol class="breadcrumb justify-content-center"><li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li><li class="breadcrumb-item"><a href="{{ route('courses') }}">Courses</a></li><li class="breadcrumb-item active">Course Details</li><li class="breadcrumb-item active">{{ $course->id }}</li></ol></div></div>
<section class="course-hero"><div class="container"><span class="badge bg-warning text-dark mb-3">{{ $course->type?->name?:'Offline Course' }}</span><h1 class="h2 text-white">{{ $course->title }}</h1><div class="d-flex flex-wrap gap-4"><span><i class="fas fa-book-open me-2"></i>Course Details</span><span><i class="fas fa-star text-warning"></i> 4.8</span><span><i class="far fa-calendar me-2"></i>{{ $course->duration?:'Flexible duration' }}</span></div></div></section>
<section class="py-5 bg-light"><div class="container"><div class="row g-4"><div class="col-lg-8"><article class="detail-card detail-description"><h3 class="h5 mb-4">More Details:</h3>{!! $course->description?:'<p>Full course information will be updated soon.</p>' !!}</article></div><aside class="col-lg-4"><div class="detail-card mb-4"><img class="w-100 rounded detail-cover mb-3" src="{{ $course->image?asset('storage/'.$course->image):asset('assets/img/bg-banner-02.png') }}" alt="{{ $course->title }}"><div class="d-flex justify-content-between"><strong class="text-success fs-4">FEE</strong><span>BDT {{ number_format($course->fee) }}</span></div><a class="btn btn-success w-100 mt-3" href="{{ route('offline-enrollments.create',['course_id'=>$course->id]) }}">ENROLL NOW</a></div><div class="detail-card mb-4"><h3 class="h6 mb-3"><i class="fas fa-building text-warning me-2"></i>Available Branch</h3><h4 class="h6">{{ $course->branch?->name }}</h4><p class="small text-muted branch-address">{{ $course->branch?->address }}</p><a class="btn btn-warning btn-sm w-100" href="{{ route('offline-enrollments.create',['course_id'=>$course->id]) }}"><i class="fas fa-paper-plane me-2"></i>Enroll</a></div><div class="detail-card"><h3 class="h6">Includes</h3><p><i class="far fa-clock text-danger me-2"></i>{{ $course->duration?:'Flexible' }}</p><p><i class="fas fa-tag text-danger me-2"></i>BDT {{ number_format($course->fee) }}</p><p class="mb-0"><i class="fas fa-car text-danger me-2"></i>{{ $course->title }}</p></div></aside></div></div></section>
@if($relatedCourses->isNotEmpty())<section class="py-5"><div class="container"><h2 class="text-center mb-5">Other Courses</h2><div class="row g-4">@foreach($relatedCourses as $item)<div class="col-lg-4 col-md-6"><div class="detail-card h-100"><img class="w-100 rounded related-cover" src="{{ $item->image?asset('storage/'.$item->image):asset('assets/img/bg-banner-02.png') }}" alt="{{ $item->title }}"><h3 class="h5 my-3">{{ $item->title }}</h3><div class="d-flex justify-content-between small mb-3"><span>BDT {{ number_format($item->fee) }}</span><span>{{ $item->duration }}</span></div><a class="btn btn-outline-primary" href="{{ route('courses.show',$item) }}">Course Details</a></div></div>@endforeach</div></div></section>@endif
<section class="faq-area bg-light py-5"><div class="container"><h2 class="text-center mb-5">Frequently Asked Questions</h2><div class="accordion mx-auto" id="courseFaq" style="max-width:850px">@foreach($faqs as $faq)<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button {{ $loop->first?'':'collapsed' }}" data-bs-toggle="collapse" data-bs-target="#course-faq-{{ $faq->id }}">{{ $faq->question }}</button></h3><div id="course-faq-{{ $faq->id }}" class="accordion-collapse collapse {{ $loop->first?'show':'' }}" data-bs-parent="#courseFaq"><div class="accordion-body">{{ $faq->answer }}</div></div></div>@endforeach</div></div></section>
@endsection
