@extends('layouts.app')
@section('title','Offline Courses Enrollment')
@section('page_styles')
<style>
.enroll-wrap{background:#f7f8fa;padding:55px 0}.enroll-panel{background:#fff;border:1px solid #dfe4eb;border-radius:6px;margin-bottom:24px}.enroll-head{padding:18px 22px;border-bottom:1px solid #e8ebef;color:#ff6e61}.enroll-body{padding:22px}.course-preview{display:flex;gap:15px;padding:14px;background:#fafafa;border-radius:8px}.course-preview img{width:135px;height:85px;object-fit:cover}.overview{border:1px solid #dde3e9;padding:20px}.form-control,.form-select{min-height:46px}.invalid-feedback{font-size:14px}.server-invalid{border-color:#dc3545!important}.server-error{display:block;color:#dc3545;margin-top:5px;font-size:14px}@media(max-width:575px){.course-preview{display:block}.course-preview img{width:100%;height:170px;margin-bottom:12px}}
</style>
@endsection
@section('content')
<div class="breadcrumb-bar breadcrumb-bar-info pt-5"><div class="container py-5 text-center"><h2>Offline Courses</h2><ol class="breadcrumb justify-content-center"><li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li><li class="breadcrumb-item">Enroll</li><li class="breadcrumb-item active">Offline Courses</li></ol></div></div>
<section class="enroll-wrap"><div class="container" style="max-width:1100px">
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the {{ $errors->count() }} highlighted {{ Str::plural('field',$errors->count()) }}.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('offline-enrollments.store') }}" enctype="multipart/form-data" class="needs-validation" novalidate>@csrf
<div class="enroll-panel"><h3 class="enroll-head h5">Student Information</h3><div class="enroll-body row g-3">
@php
$fields=[
 ['name','Name','text','Please enter your full name.','col-md-6'],['mobile','Mobile Number','tel','Enter a valid Bangladeshi mobile number.','col-md-6'],
 ['email','Email','email','Enter a valid email address.','col-md-6'],['date_of_birth','Date of Birth','date','Student must be at least 16 years old.','col-md-6'],
 ['present_address','Present Address','text','Enter at least 10 characters.','col-12'],['password','Password','password','Password must contain at least 8 characters.','col-md-6'],
 ['password_confirmation','Confirm Password','password','Passwords must match.','col-md-6']];
@endphp
<div class="col-md-6"><label class="form-label">Document Number <span class="text-danger" aria-hidden="true">*</span></label><div class="mb-2"><label><input type="radio" name="document_type" value="nid" @checked(old('document_type','nid')==='nid')> NID</label><label class="ms-3"><input type="radio" name="document_type" value="birth_certificate" @checked(old('document_type')==='birth_certificate')> Birth Certificate</label></div><input class="form-control @error('document_number') server-invalid @enderror" name="document_number" value="{{ old('document_number') }}" inputmode="numeric" required><div class="invalid-feedback">Enter a valid NID/Birth Certificate number.</div>@error('document_number')<div class="server-error">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">NID/Birth Certificate Document <span class="text-danger" aria-hidden="true">*</span></label><input class="form-control @error('document_path') server-invalid @enderror" type="file" name="document_path" accept=".jpg,.jpeg,.png,.webp" required><div class="invalid-feedback">Upload a JPG, PNG or WEBP document image.</div>@error('document_path')<div class="server-error">{{ $message }}</div>@enderror</div>
@foreach($fields as [$name,$label,$type,$feedback,$column])
<div class="{{ $column }}"><label class="form-label">{{ $label }} <span class="text-danger" aria-hidden="true">*</span></label><input class="form-control @error($name) server-invalid @enderror" type="{{ $type }}" name="{{ $name }}" @if($type!=='password') value="{{ old($name) }}" @endif @if($name==='mobile') pattern="(?:\+?88)?01[3-9][0-9]{8}" @elseif($name==='present_address') minlength="10" @elseif($name==='password') minlength="8" @elseif($name==='date_of_birth') max="{{ now()->subYears(16)->toDateString() }}" @endif required><div class="invalid-feedback">{{ $feedback }}</div>@error($name)<div class="server-error">{{ $message }}</div>@enderror</div>
@endforeach
<div class="col-12"><label class="form-label">Student Photo <small>(Optional)</small></label><input class="form-control @error('photo') server-invalid @enderror" type="file" name="photo" accept=".jpg,.jpeg,.png,.webp">@error('photo')<div class="server-error">{{ $message }}</div>@enderror</div>
</div></div>
<div class="enroll-panel"><h3 class="enroll-head h5">Course Information</h3><div class="enroll-body row g-4">
<div class="col-md-6"><label class="form-label">Course Name <span class="text-danger" aria-hidden="true">*</span></label><select class="form-select @error('course_id') server-invalid @enderror" name="course_id" id="courseSelect" required>@foreach($courses as $item)<option value="{{ $item->id }}" data-fee="{{ $item->fee }}" @selected(old('course_id',$course?->id)==$item->id)>{{ $item->title }} ({{ $item->duration }})</option>@endforeach</select>@error('course_id')<div class="server-error">{{ $message }}</div>@enderror @if($course)<div class="course-preview mt-3"><img src="{{ $course->image?asset('storage/'.$course->image):asset('assets/img/bg-banner-02.png') }}" alt="{{ $course->title }}"><div><strong>{{ $course->title }}</strong><div>Price: {{ number_format($course->fee) }} BDT</div><div>Duration: {{ $course->duration }}</div></div></div>@endif</div>
<div class="col-md-6"><label class="form-label">Branch Name <span class="text-danger" aria-hidden="true">*</span></label><select class="form-select @error('branch_id') server-invalid @enderror" name="branch_id" required><option value="">Select an Option</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id',$course?->branch_id)==$branch->id)>{{ $branch->name }}</option>@endforeach</select>@error('branch_id')<div class="server-error">{{ $message }}</div>@enderror<div class="row g-2 mt-2"><div class="col-6"><label class="form-label">Start Date <span class="text-danger" aria-hidden="true">*</span></label><input class="form-control @error('start_date') server-invalid @enderror" type="date" name="start_date" value="{{ old('start_date') }}" min="{{ now()->toDateString() }}" required>@error('start_date')<div class="server-error">{{ $message }}</div>@enderror</div><div class="col-6"><label class="form-label">Preferred Time <span class="text-danger" aria-hidden="true">*</span></label><input class="form-control @error('preferred_time') server-invalid @enderror" name="preferred_time" value="{{ old('preferred_time') }}" placeholder="e.g. 9:00 AM" required>@error('preferred_time')<div class="server-error">{{ $message }}</div>@enderror</div></div></div>
<div class="col-md-6"><div class="overview"><h4 class="h5">Enrollment Overview</h4><hr><div class="d-flex justify-content-between"><span>Course Fee:</span><strong id="courseFee">{{ number_format($course?->fee??0) }} BDT</strong></div><hr><div class="d-flex justify-content-between"><strong>Total Payable:</strong><strong class="text-danger" id="totalFee">{{ number_format($course?->fee??0) }} BDT</strong></div></div></div>
<div class="col-md-6"><label class="form-label">Payment Process <span class="text-danger" aria-hidden="true">*</span></label><select class="form-select" name="payment_method" required><option value="office" @selected(old('payment_method')==='office')>Office Payment</option><option value="online" @selected(old('payment_method')==='online')>Online Payment</option></select></div>
</div></div>
<div class="row g-3 align-items-end"><div class="col-md-6"><label class="form-label">Coupon code:</label><input class="form-control" name="coupon_code" value="{{ old('coupon_code') }}" placeholder="Enter coupon code if available"></div><div class="col-md-6 text-md-end"><button class="btn btn-primary px-5">ENROLL NOW</button></div></div>
</form></div></section>
@endsection
@push('scripts')
<script>
(()=>{const form=document.querySelector('.needs-validation');if(!form)return;const documentNumber=form.elements.document_number;function documentPattern(){const birth=form.querySelector('[name="document_type"]:checked').value==='birth_certificate';documentNumber.pattern=birth?'[0-9]{17}':'(?:[0-9]{10}|[0-9]{13}|[0-9]{17})';documentNumber.placeholder=birth?'17-digit Birth Certificate number':'10, 13 or 17-digit NID number'}documentPattern();form.querySelectorAll('[name="document_type"]').forEach(el=>el.addEventListener('change',()=>{documentPattern();documentNumber.reportValidity()}));const password=form.elements.password,confirmation=form.elements.password_confirmation;function validatePassword(){confirmation.setCustomValidity(password.value===confirmation.value?'':'Passwords do not match.')}[password,confirmation].forEach(el=>el.addEventListener('input',validatePassword));form.querySelectorAll('input,select').forEach(input=>{input.addEventListener('blur',()=>{input.classList.toggle('is-invalid',!input.checkValidity());input.classList.toggle('is-valid',input.checkValidity())});input.addEventListener('input',()=>{input.classList.remove('server-invalid');input.parentElement.querySelector('.server-error')?.remove();if(input.classList.contains('is-invalid')){input.classList.toggle('is-invalid',!input.checkValidity());input.classList.toggle('is-valid',input.checkValidity())}})});form.addEventListener('submit',event=>{validatePassword();if(!form.checkValidity()){event.preventDefault();event.stopPropagation();form.querySelector(':invalid')?.focus()}form.classList.add('was-validated')})})();
</script>
@endpush
