<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\SiteSetting;use App\Models\Testimonial;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\View\View;
class TestimonialController extends Controller {
public function index():View{return view('admin.home.testimonials',['items'=>Testimonial::orderBy('sort_order')->paginate(20),'settings'=>SiteSetting::firstOrCreate([])]);}
public function settings(Request $r):RedirectResponse{$data=$r->validate(['testimonial_title'=>['required','string','max:255'],'testimonial_subtitle'=>['nullable','string','max:500'],'testimonial_button_text'=>['required','string','max:100'],'testimonial_button_url'=>['nullable','string','max:2000'],'testimonial_background'=>['nullable','image','max:4096']]);$s=SiteSetting::firstOrCreate([]);if($r->hasFile('testimonial_background')){if($s->testimonial_background)Storage::disk('public')->delete($s->testimonial_background);$data['testimonial_background']=$r->file('testimonial_background')->store('testimonials','public');}else unset($data['testimonial_background']);$s->update($data);return back()->with('status','Testimonial section updated successfully.');}
public function store(Request $r):RedirectResponse{$data=$this->validated($r);if($r->hasFile('photo'))$data['photo']=$r->file('photo')->store('testimonials/people','public');$data['is_active']=$r->boolean('is_active');Testimonial::create($data);return back()->with('status','Review added successfully.');}
public function update(Request $r,Testimonial $testimonial):RedirectResponse{$data=$this->validated($r);if($r->hasFile('photo')){if($testimonial->photo)Storage::disk('public')->delete($testimonial->photo);$data['photo']=$r->file('photo')->store('testimonials/people','public');}$data['is_active']=$r->boolean('is_active');$testimonial->update($data);return back()->with('status','Review updated successfully.');}
public function destroy(Testimonial $testimonial):RedirectResponse{if($testimonial->photo)Storage::disk('public')->delete($testimonial->photo);$testimonial->delete();return back()->with('status','Review deleted successfully.');}
private function validated(Request $r):array{return $r->validate(['name'=>['required','string','max:255'],'review'=>['required','string','max:3000'],'rating'=>['required','integer','between:1,5'],'photo'=>['nullable','image','max:2048'],'sort_order'=>['nullable','integer','min:0']]);}}
